language: python

notifications:
  email: false

jobs:
  include:
    # perform a linux build
    # - services: docker
    # # and a mac build
    # - os: osx
    #   language: shell
    # and a windows build
    - os: windows
      language: shell

install:
  # check available python version on chocolatey: https://chocolatey.org/packages/python#versionhistory
  - docker build --tag das2py:windows-py37 . -f docker/windows/Dockerfile --build-arg PYVER=3.7.8

script:
  - export WIN_PWD=`pwd -W`
  - docker run --rm -v "${WIN_PWD}:C:/io" das2py:windows-py37 powershell cp ./dist/*.whl C:/io/dist/

# see https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci/33109519#33109519
# push wheels as github releases for testing
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    all_branches: true